export const SET_CARTLIST = 'SET_CARTLIST'

export const CLEAR_CARTLIST = 'CLEAR_CARTLIST'

export const SET_ORDERLIST = 'SET_ORDERLIST'

export const CLEAR_ORDERLIST = 'CLEAR_ORDERLIST'

export const SET_DELIVERADDRESSLIST = 'SET_DELIVERADDRESSLIST'

export const CLEAR_DELIVERADDRESSLIST = 'CLEAR_DELIVERADDRESSLIST'

export const SET_AVATAR = 'SET_AVATAR'

export const CLEAR_AVATAR = 'CLEAR_AVATAR'

export const SET_NICKNAME = 'SET_NICKNAME'

export const CLEAR_NICKNAME = 'CLEAR_NICKNAME'

export const SET_TOKEN = 'SET_TOKEN'

export const CLEAR_TOKEN = 'CLEAR_TOKEN'

export const SET_USERLEVEL = 'SET_USERLEVEL'

export const CLEAR_USERLEVEL = 'CLEAR_USERLEVEL'
